# Site settings
title: UBC Integrated Engineers
email: site@integratedengineers.ca
description: > # this means to ignore newlines until "baseurl:"
  Student run website of the UBC Integrated Engineers. This site is a resource for current students, prospective students, alumni and industry members.
baseurl: ""
url: "http://integratedengineers.ca" # the base hostname & protocol for your site
twitter_username: ubcigen
github_username:  igenubc
permalink: pretty

# Build settings
markdown: kramdown

gems:
- jekyll-auto-image

# Default image
image: /images/PresidentsUpdate.jpg
