---
title: UBC Integrated Engineers
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: site@integratedengineers.ca
description: 'Student run website of the UBC Integrated Engineers. This site is a
  resource for current students, prospective students, alumni and industry members.

'
baseurl: ''
url: http://integratedengineers.ca
twitter_username: ubcigen
github_username: ubcigen
permalink: pretty
markdown: kramdown
gems:
- jekyll-sitemap
image: "/images/truss.png"
